# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x06signal\"\xd8\x01\n\rTradingSignal\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x11\n\tstop_loss\x18\x04 \x01(\x01\x12\x13\n\x0btake_profit\x18\x05 \x01(\x01\x12\x12\n\nconfidence\x18\x06 \x01(\x01\x12\x15\n\rposition_size\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12\x14\n\x0csignal_price\x18\t \x01(\x01\x12\x18\n\x10max_slippage_bps\x18\n \x01(\x05\"@\n\tSignalAck\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"2\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\x85\x01\n\rSignalService\x12\x36\n\nSendSignal\x12\x15.signal.TradingSignal\x1a\x11.signal.SignalAck\x12<\n\x0bHealthCheck\x12\x15.signal.HealthRequest\x1a\x16.signal.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRADINGSIGNAL']._serialized_start=25
  _globals['_TRADINGSIGNAL']._serialized_end=241
  _globals['_SIGNALACK']._serialized_start=243
  _globals['_SIGNALACK']._serialized_end=307
  _globals['_HEALTHREQUEST']._serialized_start=309
  _globals['_HEALTHREQUEST']._serialized_end=324
  _globals['_HEALTHRESPONSE']._serialized_start=326
  _globals['_HEALTHRESPONSE']._serialized_end=376
  _globals['_SIGNALSERVICE']._serialized_start=379
  _globals['_SIGNALSERVICE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
